name: Build Pipeline
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      folder:
        description: 'Select the folder which contains your services'
        required: true
        type: choice
        options:
          - core-services
          - business-services
      serviceName:
        description: 'Provide the service name you want to build'
        required: true
      dbMigration:
        description: 'Enable if you require DB migration for this service'
        required: true
        type: boolean
      branch:
        description: 'Select the branch you want to build'
        required: true
        type: choice
        options:
          - master
          - core-2.9-lts-mvn-check

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract branch name and commit hash
        id: tag
        run: |
          BRANCH=${{ github.event.inputs.branch }}
          BRANCH=$(echo $BRANCH | tr -cd '[:alnum:]-_')
          COMMIT_HASH=$(git rev-parse --short HEAD || echo "no-commit")
          VERSION=$(cat .version 2>/dev/null || echo "0")

          # Increment version
          NEW_VERSION=$((VERSION + 1))
          echo $NEW_VERSION > .version

          # Export variables
          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
          echo "COMMIT_HASH=${COMMIT_HASH}" >> $GITHUB_ENV
          echo "VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          echo "::set-output name=tag::${BRANCH}-${COMMIT_HASH}-${NEW_VERSION}"

      - name: Build and push application Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/maven/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.serviceName }}:${{ env.BRANCH }}-${{ env.COMMIT_HASH }}-${{ env.VERSION }}


          build-args: WORK_DIR=${{ github.event.inputs.folder }}/${{ github.event.inputs.serviceName }}

  DB_Build:
    if: ${{ github.event.inputs.dbMigration == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract branch name and commit hash for DB
        id: tag
        run: |
          BRANCH=${{ github.event.inputs.branch }}
          COMMIT_HASH=$(git rev-parse --short HEAD || echo "no-commit")
          VERSION=${{ env.VERSION }}  # Use the same version from the first job

          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
          echo "COMMIT_HASH=${COMMIT_HASH}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "::set-output name=tag::${BRANCH}-${COMMIT_HASH}-${VERSION}"

      - name: Build and push database Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.event.inputs.folder }}/${{ github.event.inputs.serviceName }}/src/main/resources/db
          file: ${{ github.event.inputs.folder }}/${{ github.event.inputs.serviceName }}/src/main/resources/db/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.serviceName }}:${{ env.BRANCH }}-${{ env.COMMIT_HASH }}-${{ env.VERSION }}

