name: Build Pipeline
on:
  push:
    branches:
      - 'master'
      - 'core-2.9-lts-mvn-check'
  workflow_dispatch:
    inputs:
      folder:
        description: 'Select the folder which contains your services'
        required: true
        type: choice
        options:
          - core-services
          - business-services
      serviceName:
        description: 'Provide the service name you want to build'
        required: true
      dbMigration:
        description: Enable if you require DB migration for this service
        required: true
        type: boolean

jobs:
  Build:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Ensure .version exists
        run: |
          if [ ! -f .version ]; then
            echo "0" > .version
          fi

      - name: Extract branch name and commit hash
        id: tag
        run: |
          BRANCH=${GITHUB_REF##*/}
          COMMIT_HASH=$(git rev-parse --short HEAD)

          # Fallback if variables are empty
          [ -z "$BRANCH" ] && BRANCH="default-branch"
          [ -z "$COMMIT_HASH" ] && COMMIT_HASH="no-commit"

          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV

      - name: Get current version
        id: version
        run: |
          VERSION=$(cat .version)
          echo "VERSION=$VERSION"
          echo $((VERSION + 1)) > .version
          echo "::set-output name=version::$VERSION"
        shell: bash

      # - name: Archive business-services folder
      #   run: tar -czf business-services.tar.gz business-services/

      # - name: Upload business-services folder as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: business-services-artifact
      #     path: business-services.tar.gz

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/maven/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.serviceName }}:${{ env.BRANCH }}-${{ env.COMMIT_HASH }}-${{ steps.version.outputs.version }}
          build-args: WORK_DIR=${{ github.event.inputs.folder }}/${{ github.event.inputs.serviceName }}

      - name: DB Build and push
        if: ${{ github.event.inputs.dbMigration }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.event.inputs.folder }}/${{ github.event.inputs.serviceName }}/src/main/resources/db
          file: ${{ github.event.inputs.folder }}/${{ github.event.inputs.serviceName }}/src/main/resources/db/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.serviceName }}-db:${{ env.BRANCH }}-${{ env.COMMIT_HASH }}-${{ steps.version.outputs.version }}