name: Build Pipeline
on:
  workflow_dispatch:
    inputs:
      folder:
        description: 'Select the folder which contains your services'
        required: true
        type: choice
        options:
          - core-services
          - business-services
      serviceName:
        description: 'Provide the service name you want to build'
        required: true
      dbMigration:
        description: 'Enable if you require DB migration for this service'
        required: true
        type: boolean
      branch:
        description: 'Select the branch you want to build'
        required: true
        type: choice
        options:
          - master
          - core-2.9-lts-mvn-check

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Check if .version exists, else create it
      - name: Check and prepare the version file
        run: |
          if [ ! -f $GITHUB_WORKSPACE/.version ]; then
            echo "No version file found. Creating new version file."
            echo "0" > $GITHUB_WORKSPACE/.version
          else
            echo "Version file found in workspace."
          fi

      # Debugging step to check contents of .version
      - name: Debug - Check the contents of .version
        run: |
          cat $GITHUB_WORKSPACE/.version

      # Step 4: Generate a unique tag
      - name: Generate a unique tag
        id: tag
        run: |
          BRANCH=${{ github.event.inputs.branch }}
          COMMIT_HASH=$(git rev-parse --short HEAD || echo "no-commit")

          # Read or initialize the version file
          if [ -f $GITHUB_WORKSPACE/.version ]; then
            VERSION=$(cat $GITHUB_WORKSPACE/.version)
          else
            VERSION=0
          fi

          # Increment the version
          NEW_VERSION=$((VERSION + 1))
          echo $NEW_VERSION > $GITHUB_WORKSPACE/.version

          # Create the tag
          TAG="${BRANCH}-${COMMIT_HASH}-${NEW_VERSION}"

          # Export variables for the next steps
          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
          echo "COMMIT_HASH=${COMMIT_HASH}" >> $GITHUB_ENV
          echo "VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          echo "::set-output name=tag::${TAG}"

      # Step 5: Build and push application Docker image
      - name: Build and push application Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/maven/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.serviceName }}:${{ steps.tag.outputs.tag }}
          build-args: WORK_DIR=${{ github.event.inputs.folder }}/${{ github.event.inputs.serviceName }}

      # Step 6: Upload the updated .version file as an artifact
      - name: Upload the updated .version file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: version-file
          path: $GITHUB_WORKSPACE/.version
