name: Build and push

on:
  push:
    branches: ['master']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      service_name: "billing-service"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: harish7303/${{ env.service_name }}
      
      # Build and push the main Docker image for the billing service
      - name: Build and push Docker image (Main Service)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: build/maven/Dockerfile
          push: true
          tags: harish7303/${{ env.service_name }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            WORK_DIR=business-services/billing-service

      # Build and push the db image for the billing service
      - name: Build and push Docker image (DB Service)
        uses: docker/build-push-action@v4
        with:
          context: business-services/billing-service/src/main/resources/db
          file: business-services/billing-service/src/main/resources/db/Dockerfile
          push: true
          tags: harish7303/${{ env.service_name }}-db:latest
          labels: ${{ steps.meta.outputs.labels }}
